export default {
  init: false,
  name: "",
  error: null,
  board: null,
  comments: null,
  config: null,
  ptnUI: { branchPointOverrides: {} },
  history: null,
  historyIndex: 0,
  list: [],
  position: null,
  ptn: null,
  selected: null,
  editingTPS: undefined,
  highlighterEnabled: false,
  highlighterSquares: {},
  arrowsEnabled: false,
  highlighterArrows: [],
  // Temporary annotation layer, drawn with the Shift/Ctrl modifier keys.
  // Never persisted; cleared whenever the position changes.
  tempHighlighterSquares: {},
  tempHighlighterArrows: [],
  hlSquares: [],
  hoveredSquare: null,
  evaluation: null,
  evaluationWDL: null,
  analyzedPositions: {},
};
