export default {
  init: false,
  name: "",
  error: null,
  board: null,
  comments: null,
  config: null,
  ptnUI: { branchPointOverrides: {} },
  history: null,
  historyIndex: 0,
  list: [],
  position: null,
  ptn: null,
  selected: null,
  editingTPS: undefined,
  highlighterEnabled: false,
  highlighterSquares: {},
  hlSquares: [],
  hoveredSquare: null,
  evaluation: null,
  evaluationWDL: null,
  analyzedPositions: {},
};
